### DISCUSSION TITLE
Zsh prompt to fish?

### DISCUSSION THREAD

**Discussion by ddbnl** [JaKooLit/Hyprland-Dots#343] [Q&A]
First of all thanks for the fantastic dot, enjoying it a lot.

I like the prompt that comes in Zsh, but I would like to use Fish. Is there any way to take this prompt to other shells?

Thanks!

**Comment by JaKooLit** [comment]
yw

im not sure if fish has a theme that looks like the zsh theme.

you could check out here

https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md

**Comment by JohnRTitor** [comment]
Perhaps just convert the config to starship and use that?

**Reply by JaKooLit** [reply]
I dont know... I dont use fish so Im not certain

**Reply by ddbnl** [reply]
Looking into it, this might be the best way, I'll give it a shot today or tomorrow. If it works out i'll post here for anyone else that might want the same thing. Thanks!

**Reply by JohnRTitor** [reply]
If you use NixOS you can try out my starship prompt,

https://github.com/JohnRTitor/nix-conf/blob/hyprland/home-manager/shell/starship.nix

Note that you'd need a nerd font installed

**Reply by ddbnl** [reply]
Managed to write it in starship:

![image](https://github.com/JaKooLit/Hyprland-Dots/assets/40169436/2048555d-b9e9-4c16-b428-78d55aad112f)

Probably no way to PR it since it would add a dependency, but perhaps it saves someone some time by copy pasting the below:


~/.config/starship.toml
```toml
"$schema" = 'https://starship.rs/config-schema.json'

palette = 'abc'

format = '''
[┌─\[](blue)$username[@](magenta)$hostname[\]](blue) $os[-](magenta) [\[](blue)$directory[\]](
blue) [-](magenta) [\[](blue)$time[\]](blue)
[└─\[](blue)[$](magenta)[\]](blue) [<](blue)$git_branch[>](blue) 
'''

# Inserts a blank line between shell prompts
add_newline = true

[username]
show_always = true
format = '[$user](green)'

[hostname]
ssh_only = false
format = '[$hostname](lightblue)'

[directory]
disabled = false
format = '[$path]($style)'
style = 'white'
truncate_to_repo = false

[time]
format = '[$time]($style)'
style = 'yellow'
time_format = '%a %b %d, %H:%M'
disabled = false

[git_branch]
format = '[git: \(](blue)[$symbol](magenta)[$branch\)](blue)'

[palettes.abc]
blue = '#0E7ABB'
white = '#CACBCC'
lightblue = '#15C0C1'
magenta = '#BC22C4'
green = '#20BB0A'
yellow = '#BCBC07'
```

~/.config/fish/config.fish
```
if status is-interactive
    starship init fish | source
    set fish_color_valid_path green
    set fish_color_invalid_path red
    # Commands to run in interactive sessions can go here
end
```
